# DO NOT USE FOR PRODUCTION
version: "3.8"
services:
  api:
    container_name: api
    build: .
    tty: true
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./
        target: /app
      - /app/node_modules
    command:
      - "yarn"
      - "start:dev"
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongoDataStore:/data/db

volumes:
  mongoDataStore:
    driver: local
